### ISSUE TITLE
Ally requests is spamming no matter what you chose to respond.

### ISSUE THREAD

**Issue by erik1988** [phaed420/SimpleClans#249] opened 2015-03-30 19:13 UTC
Ally invite just keeps spaming the users with the deny/accept message. If they click accept many times it just adds them many times to the list. The only thing to do is to restart the servere, then its back next time someone offer an alliance.

**Comment by erik1988** [comment] 2015-03-30 19:14
I used Build #83

**Comment by phaed420** [comment] 2015-03-31 17:59
try latest, see if that did it

**Comment by phaed420** [comment] 2015-03-31 18:01
Duplicate of issue #248

**Closed by phaed420** 2015-03-31 18:01 UTC
